### ISSUE TITLE
USER STORY: Navigation

### ISSUE THREAD

**Issue by SimasJakubenas** [SimasJakubenas/movie-roulette-pp4#2]
As a **new user** I can **navigate the site effortlessly** so that I can **get to the area of interest quickly**.

### Acceptance Criteria
1. Menu should be displayed at the top of the page
2. Different menu options available depending on login status
3. Hamburger icon with a drop down menu is displayed for medium size and smaller screens

### Tasks:

- [ ] Add menu list
- [ ] Add logic to restrict menu items depending on login status
- [ ] Add hamburger icon and JS for menu toggling
